name: Build and Deploy Docker Image (Self-Hosted)

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: [self-hosted, build, deploy]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set Docker image tag
        run: echo "IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/my-php-app:${{ github.sha }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            -t $IMAGE_TAG \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/my-php-app:latest \
            -f smartedu/Dockerfile smartedu

      - name: Push Docker images
        run: |
          docker push $IMAGE_TAG
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-php-app:latest

      - name: Stop and remove any existing container
        run: |
          docker rm -f php-app || true

      - name: Run Docker container on port 80
        run: |
          docker run -d -p 80:80 --name php-app ${{ secrets.DOCKERHUB_USERNAME }}/my-php-app:latest
