name: Build and Deploy Docker Image (Self-Hosted)

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: [self-hosted, build, deploy]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-php-app:latest -f smartedu/Dockerfile smartedu

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-php-app:latest
