name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Ensure Docker is Running
      run: |
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Clean Docker system
      run: |
        docker system prune -a -f --volumes || true

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Verify Build Context
      run: ls -l smartedu/

    - name: Build Docker image
      run: |
        docker buildx build --load --cache-from=type=registry,ref=bulawesley/smartedu:cache \
          --cache-to=type=inline \
          -t bulawesley/smartedu:v${{ github.run_number }} -f smartedu/Dockerfile smartedu/

    - name: List Docker Images (Debug)
      run: docker images

    - name: Push Docker image
      run: |
        docker push bulawesley/smartedu:v${{ github.run_number }}

    - name: Deploy Application
      run: |
        docker stop smartedu-app || true
        docker rm smartedu-app || true
        docker pull bulawesley/smartedu:v${{ github.run_number }}
        docker run -d --name smartedu-app -p 4566:80 bulawesley/smartedu:v${{ github.run_number }}

    - name: Install and Start Ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update && sudo apt install ngrok -y
        ngrok authtoken ${{ secrets.NGROK_TOKEN }}
        ngrok http 4566 --log=stdout > ngrok.log 2>&1 &

    - name: Wait for Ngrok to Start (6 minutes)
      run: sleep 360

    - name: Debug Ngrok Log
      run: cat ngrok.log

    - name: Display Ngrok URL
      run: |
        curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'
